nstest.web/Models/ErrorViewModel.cs
using System;

namespace nstest.web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

nstest.web/Models/XKCDDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nstest.web.Models
{
    public class XKCDDTO
    {
        public int num { get; set; }
        public string alt { get; set; }
        public string img { get; set; }
        public string title { get; set; }        
    }
}

nstest.web/ViewModels/ComicViewModel.cs
using nstest.model.Concrete;
using nstest.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace nstest.web.ViewModels
{
    public class ComicViewModel: XKCDDTO
    {
        public int PreviousComicId { get; set; }
        public int CurrentComicId { get; set; }
        public int NextComicId { get; set; }
        public bool Unavailable { get; set; }
        public bool IsTheFirstOne { get; set; }
        public bool GoBackToCurrent { get; set; }
        public async Task<ComicViewModel> GetComic(int id, int currentId)
        {
            try
            {
                var viewModel = new ComicViewModel();

                if (id >= currentId)
                {
                    viewModel.GoBackToCurrent = true;
                    return viewModel;
                }

                var raw = await XKCD.GetComic(id);

                if (raw == null)
                {
                    viewModel.Unavailable = true;
                    return viewModel;
                }
                if (id == 1)
                    viewModel.IsTheFirstOne = true;
              
                viewModel.PreviousComicId = 0;
                viewModel.NextComicId = id + 1;
                if (raw.num > 0)
                    viewModel.PreviousComicId = raw.num - 1;

                viewModel.title = raw.title;
                viewModel.img = raw.img;

                return viewModel;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

nstest.web/ViewModels/HomeViewModel.cs
using nstest.model.Concrete;
using nstest.web.Models;
using System;
using System.Threading.Tasks;

namespace nstest.web.ViewModels
{
    public class HomeViewModel : XKCDDTO
    {
        public int PreviousComicId { get; set; }
        public int CurrentComicId { get; set; }
        public int NextComicId { get; set; }
        public async Task<HomeViewModel> GetMostRecentComic()
        {
            try
            {
                var raw = await XKCD.GetMostRecentComic();

                var viewModel = new HomeViewModel();

                var previousComicId = 0;

                if (raw.num > 0)
                    previousComicId = raw.num - 1;

                viewModel.PreviousComicId = previousComicId;
                viewModel.CurrentComicId = raw.num;

                viewModel.title = raw.title;
                viewModel.img = raw.img;

                return viewModel;
            }
            catch (Exception ex)
            {
                throw;
            }

        }
    }
}

nstest.web/Controllers/ComicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using nstest.web.ViewModels;

namespace nstest.web.Controllers
{
    public class ComicController : Controller
    {
        [Route("comic/{id:int}")]
        public async Task<IActionResult> Index(int id)
        {
            int currentComicId = Convert.ToInt32(TempData["CurrentComicId"]);          

            var viewModel = await new ComicViewModel().GetComic(id, currentComicId);

            TempData["CurrentComicId"] = currentComicId;

            if (viewModel.GoBackToCurrent)
                return RedirectToAction("Index", "Home");
            if (viewModel.Unavailable)
                return RedirectToAction("Index", new { id = id + 1 });

            return View(viewModel);
        }
    }
}

nstest.web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using nstest.web.Models;
using nstest.web.ViewModels;

namespace nstest.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = await new HomeViewModel().GetMostRecentComic();

            TempData["CurrentComicId"] = viewModel.CurrentComicId;
            
            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

nstest.web/Views/Comic/Index.cshtml
@model nstest.web.ViewModels.ComicViewModel
@{
    ViewData["Title"] = "nsTest";
}

<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">

                </div>
                <div class="card-body align-content-center">
                    <div>
                        <img src="@Model.img" alt="@Model.title" style="height: 100%; width: 100%;">
                    </div>
                    <div>
                        <span> Title: @Model.title</span>
                    </div>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>     
    </div>
    <div class="row col-xs-12" style="display: flex;">
        <div class="col-xs-2" style="display: inline-block;">
            @if (!@Model.IsTheFirstOne)
            {
                <a asp-controller="Comic"
                   asp-action="Index"
                   asp-route-id="@Model.PreviousComicId"
                   title="@Model.title"
                   style="padding-top:10px;padding-left:15px;">Previous</a>
            }
        </div>
        <div class="col-xs-6" style="display: inline-block;width: 50%;"></div>
        <div class="col-xs-2" style="display: inline-block;justify-content:end;">
            <a asp-controller="Comic"
               asp-action="Index"
               asp-route-id="@Model.NextComicId"
               asp-title="@Model.title"
               style="padding-top: 10px;">Next</a>
        </div>
    </div>
</div>

nstest.web/Views/Home/Index.cshtml
@model nstest.web.ViewModels.HomeViewModel
@{
    ViewData["Title"] = "nsTest";
}

    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body align-content-center">
                        <div>
                            <img src="@Model.img" alt="@Model.title" style="height: 100%; width: 100%;">
                        </div>
                        <div>
                            <span> Title: @Model.title</span>
                        </div>                        
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>            
        </div>
        <div class="row"> 
            <div style="padding-left: 20px; padding-top: 10px;">
                <a asp-controller="Comic"
                   asp-action="Index"
                   asp-route-id="@Model.PreviousComicId"
                   title="@Model.title">Previous</a>
            </div>
        </div>
    </div>

nstest.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - nstest.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">nstest.web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - nstest.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>